import { Link, createFileRoute } from "@tanstack/react-router";

import { asset, whatsappUrl } from "../content";

export const Route = createFileRoute("/heritage")({ component: HeritagePage });

function HeritagePage() {
  return (
    <main>
      <section className="page-hero photo-page-hero heritage-hero"><img className="page-hero-image" src={asset("journal/eco-08.webp")} width="790" height="445" alt="A group gathering in the Long Taa longhouse" /><div className="page-hero-shade" /><div className="page-hero-content"><p className="eyebrow">Our story & living heritage</p><h1>A living village, not a tourist resort.</h1><p className="lead">Long Taa is a traditional 20-door longhouse and home of the Indigenous Sebup community in Ulu Tinjar, Baram, Sarawak.</p></div></section>
      <section className="content-section story-section"><img src={asset("community-meal.webp")} width="592" height="444" loading="lazy" alt="A shared meal in the Long Taa community setting" /><div><p className="section-label">Why the eco-stay exists</p><h2>Share beauty. Support community-led conservation.</h2><p>Long Taa Borneo Eco Stay was created to share the natural beauty, Indigenous culture and traditional ways of life of Long Taa with visitors, while supporting community-based conservation and sustainable rural development.</p><p>Culture here is living identity, not a display. Community rules and local guidance shape every respectful visit.</p></div></section>
      <section className="content-section values-grid"><article><p className="card-kicker">01</p><h3>Protect nature</h3><p>River conservation, forest stewardship and wildlife protection are part of the community's relationship with this landscape.</p></article><article><p className="card-kicker">02</p><h3>Respect culture</h3><p>Visitors are guests in a living community. Follow Sebup customs, conservation-area guidance and community rules.</p></article><article><p className="card-kicker">03</p><h3>Share heritage</h3><p>Long Taa offers the chance to learn through an unhurried visit, conversation and presence in the place.</p></article></section>
      <section className="content-section heritage-image-pair"><img src={asset("journal/eco-21.webp")} width="668" height="376" loading="lazy" alt="Visitors taking in the Long Taa landscape" /><img src={asset("journal/eco-22.webp")} width="668" height="501" loading="lazy" alt="A quiet viewpoint over the Long Taa landscape" /></section>
      <section className="content-section respect-panel"><div><p className="section-label">Visit with respect</p><h2>Come curious. Listen closely. Follow local guidance.</h2></div><ul><li>Respect conservation areas, Sebup customs, culture and community rules.</li><li>Ask before photographing people, homes, activities or sensitive places.</li><li>Understand that access, activities and appropriate behaviour are guided by the community.</li></ul></section>
      <section className="content-section recognition-panel"><p className="section-label">Community recognition</p><h2>Care for the Dapui River has been recognised.</h2><p>On 1 September 2026, <a href="https://www.theborneopost.com/2026/09/01/sebup-communitys-efforts-to-preserve-dapui-river-recognised-with-award/" target="_blank" rel="noreferrer">The Borneo Post reported</a> that the Sebup community received the Gamuda Inspiration Award for Environment and Wildlife for work centred on the Dapui River tagang system and broader community conservation.</p><p className="fine-print">This is an attributed news report, not a certification or a claim about visitor outcomes.</p></section>
      <section className="closing-panel content-section"><p className="section-label">Plan a respectful visit</p><h2>Your journey starts with a conversation.</h2><p>Share what you are hoping to experience and Long Taa can help you plan within local conditions and availability.</p><div className="actions"><a className="primary-action dark-action" href={whatsappUrl} target="_blank" rel="noreferrer">Book on WhatsApp</a><Link className="secondary-action on-dark" to="/plan">Plan your journey</Link></div></section>
    </main>
  );
}
